# EPUB電子版用の上書き設定
# EPUBビルド時のコマンド
# root@UBUNTU:/mnt/d/Dropbox/Git2/book_Caesar_concise_en/articles# docker run --rm -v `pwd`:/work vvakame/review:5.8 /bin/sh -c "gem install unicode-display_width && cd /work && review-epubmaker config-epub.yml"

# 継承元設定
inherit: ['config.yml']

# 電子版を別のファイル名にしたい場合
#bookname: book_Caesar_concise_en

date: 2025-07-20
history: [['2025-07-20 A Concise Edition（EPUB）v1.0.0']]

titlefile: title.xhtml

# B5電子配布版　【本番用】
#texdocumentclass:
#  [
#    'review-jsbook',
#    'media=ebook,paper=b5, serial_pagination=true,hiddenfolio=nikko-pc,openany, fontsize=10pt,baselineskip=15.4pt,line_length=40zw,number_of_lines=42, head_space=15mm,headheight=5mm, headsep=2mm,footskip=7mm',
#  ]
# B5電子配布版　【ドラフト用】
#texdocumentclass: ["review-jsbook", "media=ebook,paper=b5, serial_pagination=true,hiddenfolio=nikko-pc,openany, fontsize=10pt,baselineskip=15.4pt,line_length=40zw,number_of_lines=42, head_space=15mm,headheight=5mm, headsep=2mm,footskip=7mm, draft"]

## 以下デフォルトの設定.
# B5の設定(10pt 40文字×35行) - 電子版
#texdocumentclass: ["review-jsbook", "media=ebook,paper=b5,serial_pagination=true,openany,fontsize=10pt,baselineskip=15.4pt,line_length=40zw,number_of_lines=35,head_space=30mm,headsep=10mm,headheight=5mm,footskip=10mm"]
# A5の設定(9pt 38文字×37行) - 電子版
# texdocumentclass: ["review-jsbook", "media=ebook,paper=a5,serial_pagination=true,openany,fontsize=9pt,baselineskip=13pt,line_length=38zw,number_of_lines=37,head_space=15mm,headsep=3mm,headheight=5mm,footskip=10mm"]
